project_id = "pxovrwladvrkftlorcuy"

[functions.check-deadlines]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true

[functions.notify-demand-request]
verify_jwt = true
